### ISSUE TITLE
The "NOT" symbol in REXX exec CUST1 is not correct.

### ISSUE THREAD

**Issue by zArchitectBill** [cicsdev/cics-genapp#1]
This may well be a matter of codepage conversion, but the "NOT" symbol that should have been a "¬" came out as a "^"  (carat, above the 6 on my Macbook). When running the script on z/OS, it threw an error about an invalid character. Once I edited the exec and changed the characters to a ¬, it worked fine.  I didn't see any kind of warning in the README.  It appears to be a "^" here in the Github source also. Not sure what went awry...may need to fix in the code here.

**Comment by ian-burnett** [comment]
Thanks for pointing this out.

Almost certainly a codepage issue - I think the backslash character is much more reliable when using Rexx across multiple code pages.

Ian

**Comment by zArchitectBill** [comment]
I guess I'm old-timey.  I'm used to using that little hook thing.  :-) Thanks for taking a look at it!

**Comment by ian-burnett** [comment]
Reopening this - it's still something worth fixing.

Ian

**Comment by ian-burnett** [comment]
Should be resolved by #2 - would you like to try this out @zArchitectBill ?

**Comment by zArchitectBill** [comment]
Thanks, Ian. I did try and the script ran without error.  Can close now.
