### ISSUE TITLE
Building.md: Specify required versions for dependencies

### ISSUE THREAD

**Issue by augmented-fog** [cicsdev/cics-genapp#11]
Hello,
What major versions of each software component are required for building?

**Comment by PhilWakelin** [comment]
Thanks for raising the issue.
The CICS TS pre-req is listed [here ](https://github.com/cicsdev/cics-genapp/blob/main/README.md)for this repo. Then for each version of CICS TS the supported software can be found on this [site](https://www.ibm.com/support/pages/detailed-system-requirements-cics-ts-and-related-products)
Let us know if you think anymore information is required @augmented-fog

**Comment by augmented-fog** [comment]
What dialect and version of COBOL is in use in this repository?

**Comment by markcocker** [comment]
@augmented-fog You will need IBM Enterprise COBOL - any supported version should work. The example compile job [JCL](/cicsdev/cics-genapp/blob/main/base/cntl/cobol.jcl) uses PGM=IGYCRCTL that is provided by [Enterprise COBOL](https://www.ibm.com/docs/en/cobol-zos/6.4?topic=jcl-writing-compile-programs).

**Comment by augmented-fog** [comment]
Thank you, this answers my question.
