### ISSUE TITLE
LGAPDB01 suffers an S0C7 abend

### ISSUE THREAD

**Issue by JAMOGRAD** [cicsdev/cics-genapp#8]
LGAPDB01 is the COBOL program called to add a policy. SSP1, option 2.

The policy number does not exist yet, as it is created by Db2, so it is not passed to the program in the COMMAREA.

MOVE CA-POLICY-NUM   TO DB2-C-PolicyNum-INT

CA-POLICY-NUM is defined as a Zoned Decimal Number (USAGE DISPLAY). Unfortunately as it is not set from the initial BMS map, it is uninitialised storage. 

This results in an S0C7 abend (Data Exception).

Changing that line to 

MOVE ZERO            TO DB2-C-PolicyNum-INT

Fixes it.

**Comment by ledina** [comment]
@JAMOGRAD that might be fixed with the latest changes from Tom. Can you please verify?

**Comment by JAMOGRAD** [comment]
@ledina I can indeed see that the fix is in! Happy to close on that basis!
